const  actionTypes = {
    LOGIN:'LOGIN',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAIL:'REGISTER_FAIL',
    LOGOUT:'LOGOUT',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    GET_CURRENT_USER:'GET_CURRENT_USER',

    GET_CATEGORY:'GET_CATEGORY',

    GET_POST : 'GET_POST',
    
    GET_PROVINCE : 'GET_PROVINCE',
    GET_DISTRICT : 'GET_DISTRICT',
    GET_WARD : 'GET_WARD',

    SEARCH : 'SEARCH'

}
export default actionTypes